---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/ha-card-build.yml@065e689c85cec1e7d025f6d074b2589e41d6bb2b # master
