---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/ha-card-build.yml@490c64c3f555afa983a7553d22e95a53a46fafbb # master
