---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  oxlint:
    uses: timmo001/workflows/.github/workflows/lint-oxlint.yml@dee521f49caa2626c8adeed2af4767887b2f202b # 20261009.1
    with:
      package-manager: pnpm
