---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  oxlint:
    uses: timmo001/workflows/.github/workflows/lint-oxlint.yml@942a2e735c957787562e621d916fb6f78c9bb508 # 20261009.0
    with:
      package-manager: pnpm
