---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  oxlint:
    uses: timmo001/workflows/.github/workflows/lint-oxlint.yml@f8d0daf26e163f0ee997d759fbf0f7daeb598c43 # 20261008.2
    with:
      package-manager: pnpm
