---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master
    with:
      dist-glob: "dist/ha-dashboard-maintenance.js"
    permissions:
      contents: write
