---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@d220b93d3fb3dd498b56bd562bba64b0a00073b8 # master
    with:
      dist-glob: "dist/ha-dashboard-maintenance.js"
    permissions:
      contents: write
