---
name: HACS Validate

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  validate:
    uses: timmo001/workflows/.github/workflows/ha-card-validate.yml@2b050288cd02492c371a6ef5269817db163c002b # master
