---
name: HACS Validate

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  validate:
    uses: timmo001/workflows/.github/workflows/ha-card-validate.yml@0f94251168336b74fadf271a955d24d1de4de343 # 20260927.1
